#!/usr/bin/env pwsh

[CmdletBinding()]
param (
  [Parameter(Mandatory, Position = 0)]
  [Version]
  $Version,

  [Parameter()]
  [Switch]
  $Prerelease
#   [Parameter(Mandatory, Position = 0)]
#   [ValidateSet('major', 'minor', 'build')]
#   [String]
#   $ReleaseType
)

# $Version =
#   git tag --list v* `
#   |% { $_ -replace '^v([^-]+).*$', '$1'} `
#   |% { [Version]$_ } `
#   | Select-Object -Unique `
#   | Sort-Object  -Descending `
#   | Select-Object -First 1

# switch ($ReleaseType) {
#   'major' {

#   }
# }

$Tag = "v${Version}"
if ($Prerelease) {
  $Tag += '-pre'
}

git tag $Tag -m $Tag
git push origin $Tag