#!/bin/sh
# trap 'kill $MONGOPID; exit' INT

DATA=$TMPDIR
MONGO_DB=$DATA/mongo

mkdir -p $MONGO_DB
mongod --dbpath $MONGO_DB #&
# MONGOPID=$!

# mkdir -p $TMPDIR/azurite
# npx azurite --location $TMPDIR/azurite