name: dev
on:
  pull_request:
    branches-ignore: [ release/* ]
  push:
    branches: [ dev ]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 0
  DOTNET_NOLOGO: 1
  RESTFU_CONFIGURATION: Release
  RESTFU_PACKAGE_PATH: .nupkg

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

    - name: Restore, Build, and Test
      env:
        MONGODB_URL: ${{ secrets.MONGODB_URL }}
      run: dotnet test

    - name: Package
      if: github.ref == 'refs/heads/dev'
      run: dotnet pack

    - name: Setup GitHub Packages API Key
      if: github.ref == 'refs/heads/dev'
      uses: actions/setup-dotnet@v1
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        source-url: https://nuget.pkg.github.com/juliekoubova/

    - name: Upload to GitHub Packages
      if: github.ref == 'refs/heads/dev'
      working-directory: ${{ env.RESTFU_PACKAGE_PATH }}
      run: >
        dotnet nuget push '*.nupkg'
        --no-symbols=true
        --source Source
