name: Release Development Packages
on:
  pull_request:
  push:

env:
  Configuration: Release
  DOTNET_CLI_TELEMETRY_OPTOUT: 0
  DOTNET_NOLOGO: 1
  PackageOutputPath: .nupkg

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201

    - name: Restore, Build, and Test
      env:
        MONGODB_URL: ${{ secrets.MONGODB_URL }}
      run: dotnet test

    - name: Package
      if: github.ref == 'refs/heads/dev'
      run: dotnet pack

    - name: Upload to GitHub Packages
      if: github.ref == 'refs/heads/dev'
      shell: pwsh
      run: |
        gci env:\
        Get-ChildItem $Env:PackageOutputPath\*.nupkg |% {
          curl -X PUT `
            -u "juliekoubova:${{ secrets.GITHUB_TOKEN }}" `
            -F package=@$_ `
            https://nuget.pkg.github.com/juliekoubova/
        }
