name: Publish to NuGet.org
on:
  push:
    branches:
        publish

env:
  Configuration: Release
  DOTNET_CLI_TELEMETRY_OPTOUT: 0
  DOTNET_NOLOGO: 1
  PackageOutputPath: ${{ github.workspace }}\.nupkg

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201

    - name: Restore, Build, and Test
      env:
        MONGODB_URL: ${{ secrets.MONGODB_URL }}
      run: dotnet test

    - name: Package
      run: dotnet pack

    - name: Upload to NuGet.org
      working-directory: ${{ env.PackageOutputPath }}
      run: dotnet push *.nupkg -k "${{ secrets.NUGET_KEY }}"