name: release
on:
  push:
    branches:
      release/*

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 0
  DOTNET_NOLOGO: 1
  RESTFU_CONFIGURATION: Release
  RESTFU_PACKAGE_PATH: .nupkg

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

    - name: Restore, Build, and Test
      env:
        MONGODB_URL: ${{ secrets.MONGODB_URL }}
      run: dotnet test

    - name: Package
      run: dotnet pack

    - name: Upload to NuGet.org
      working-directory: ${{ env.RESTFU_PACKAGE_PATH }}
      run: >
        dotnet nuget push '*.nupkg'
        --api-key '${{ secrets.NUGET_KEY }}'
        --no-symbols=true
        --source nuget.org
